// <auto-generated />
using System;
using GoTrainingPlatform.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoTrainingPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(GoTrainingPlatformDbContext))]
    [Migration("20260805032820_AddXminConcurrencyTokenToGame")]
    partial class AddXminConcurrencyTokenToGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoTrainingPlatform.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BoardSize")
                        .HasColumnType("integer")
                        .HasColumnName("board_size");

                    b.Property<int>("BotStrength")
                        .HasColumnType("integer")
                        .HasColumnName("bot_strength");

                    b.Property<double>("Komi")
                        .HasColumnType("double precision")
                        .HasColumnName("komi");

                    b.Property<int?>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<int>("PlayerColor")
                        .HasColumnType("integer")
                        .HasColumnName("player_color");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("GoTrainingPlatform.Domain.Game", b =>
                {
                    b.OwnsMany("GoTrainingPlatform.Domain.Move", "Moves", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid")
                                .HasColumnName("game_id");

                            b1.Property<int>("MoveNumber")
                                .HasColumnType("integer")
                                .HasColumnName("move_number");

                            b1.HasKey("GameId", "MoveNumber")
                                .HasName("pk_moves");

                            b1.ToTable("moves", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GameId")
                                .HasConstraintName("fk_moves_games_game_id");

                            b1.OwnsOne("GoTrainingPlatform.Domain.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("MoveGameId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("game_id");

                                    b2.Property<int>("MoveNumber")
                                        .HasColumnType("integer")
                                        .HasColumnName("move_number");

                                    b2.Property<int>("X")
                                        .HasColumnType("integer")
                                        .HasColumnName("coordinates_x");

                                    b2.Property<int>("Y")
                                        .HasColumnType("integer")
                                        .HasColumnName("coordinates_y");

                                    b2.HasKey("MoveGameId", "MoveNumber");

                                    b2.ToTable("moves");

                                    b2.WithOwner()
                                        .HasForeignKey("MoveGameId", "MoveNumber")
                                        .HasConstraintName("fk_moves_moves_game_id_move_number");
                                });

                            b1.Navigation("Coordinates");
                        });

                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
